# Generated by Django 2.2.2 on 2019-07-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('pick_up_loc', models.CharField(max_length=200)),
                ('drop_off_loc', models.CharField(max_length=200)),
                ('Reason_firsttime', models.CharField(max_length=200)),
                ('first_time', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=25)),
                ('sex', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=50)),
                ('health_ins', models.CharField(max_length=50)),
                ('MTS_reason', models.CharField(max_length=50)),
                ('n_hlth_appt', models.IntegerField(default=5)),
                ('hlth_appt_score', models.IntegerField(default=3)),
                ('n_missed_appt', models.IntegerField(default=3)),
                ('missed_appt_score', models.IntegerField(default=3)),
                ('ER', models.CharField(max_length=10)),
                ('n_ER_visit', models.IntegerField(default=3)),
                ('diabetes_diag', models.CharField(max_length=10)),
                ('pre_diab_diag', models.CharField(max_length=10)),
                ('health_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('Question_1', models.CharField(max_length=200)),
                ('Question_2', models.CharField(max_length=200)),
                ('Question_3', models.CharField(max_length=200)),
                ('Question_4', models.CharField(max_length=200)),
            ],
        ),
    ]
